---
version: '2'
services:
  web:
   build: web
   ports:
     - "443:443"
   depends_on:
     - wordpress
   volumes:
     - ./dev/code/app:/var/www/html/app/

  wordpress:
   build: wordpress
   volumes:
     - ./wordpress/code:/code   
   depends_on:
     - redis

