---
version: '3'
services:
  lb:
   build: lb
   ports:
     - "443:443"
   depends_on:
     - web

  web:
   build: web
   depends_on:
     - wordpress
   volumes:
     - ./dev/code/app:/var/www/html/app/
   depends_on:
     - wordpress

  wordpress:
   image: wordpress:latest
    depends_on:
     - db
   
  db:
   image: mariadb:latest
   volumes_from:
     - data-mysql
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: xxxx
     MYSQL_DATABASE: xxxx
     MYSQL_USER: xxxx
     MYSQL_PASSWORD: xxxx
